apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmith-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsmith-db
  template:
    metadata:
      labels:
        app: wordsmith-db
    spec:
      containers:
      - name: db
        image: jpetazzo/wordsmith-db:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: "trust"
