apiVersion: apps/v1
kind: Deployment
metadata:
  name: words-deployment
  labels:
    app: words
spec:
  replicas: 1
  selector:
    matchLabels:
      app: words
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
      - name: words
        image: wordsmith-words # Remplacez par le nom de votre image Docker et le tag pour words
        ports:
        - containerPort: 8080


