name: Build and Push Docker Images
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
   types: [labeled]
   
jobs:
  build-and-push:
   runs-on: ubuntu-latest
   strategy:
    matrix:
     include:
      - image_name: db
        dockerfile: db/dockerfile
        context: ./db
      - image_name: web
        dockerfile: web/dockerfile
        context: ./web
      - image_name: words
        dockerfile: words/dockerfile
        context: ./words
   steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: yassineberriri
        password: dckr_pat_t8W62BdV7xZJjwbtOReuA1pSbWc

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ./${{ matrix.dockerfile }}
        push: true
        tags: yassineberriri/${{ matrix.image_name }}:db, yassineberriri/${{ matrix.image_name }}:web, yassineberriri/${{ matrix.image_name }}:words
        load: false